#!/bin/bash
# Copyright © 2017 Alexander Sosna <alexander.sosna@credativ.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# This is to automatic tune PostgreSQL cloud images for first use, nothing more!

set -e

# Settings
grubcfg="testdata/grub"
pgconf="testdata/postgresql.conf"
pgversion="9.5"
pgclustername="main"


# set_option_in_file changes lines in a file in order to change configuration options.
# It takes 3 arguments:
#    $1: path to configuration file
#    $2: identifier string that identifies the target option
#    $3: full option line as it should appear in the config file
function set_option_in_file()
{
    file=$1
    identifier=$2
    option=$3

    if grep -q "$option" $file; then
        echo "$file: Found option: $option, nothing to do."
    elif grep -q "$identifier" $file; then
        echo "$file: Found identifier: $identifier, going to replace with option: $option"
        sed -i -e "/$identifier/ c $option" $file
    else
        echo "$file: Put option at end of file: $option"
        echo "$option" >> $file
    fi
}

# Change grub configuration
function configure_grub()
{
    set_option_in_file "$grubcfg" "$1" "$2"
}

# Change PostgreSQL configuration
function configure_postgresql()
{
    # If pg_conftool is available use it, otherwise modify the file.
    if command -v pg_conftool >/dev/null 2>&1; then
        pg_conftool "$pgconf" set "$1" "$2"
    else
        set_option_in_file "$pgconf" "\b${1} =" "$1 = $2"
    fi
}

function gen_shared_buffers() {
        $(( $total_mem_MB / 4 ))
    if (( $shared_buffers_MB > 12000 ))
    then
        shared_buffers_MB=12000
    fi
}

# Autoconf
cpucount=$(nproc)
total_mem_kB=$(cat /proc/meminfo | grep MemTotal | awk '{ print $2 }')
total_mem_MB=$(( $total_mem_kB / 1000 ))

echo "CPU count: $cpucount"
echo "Memory: $total_mem_MB MB"

shared_buffers_MB = genshared_buffers()

work_mem_MB=32
maintenance_work_mem_MB=512
autovacuum_max_workers=$(( $cpucount + 2 ))

if (( $total_mem_MB < 1900 ))
then
    echo "Configure for micro instance!"
    shared_buffers_MB=128
    work_mem_MB=4
    maintenance_work_mem_MB=64
    effective_cache_size_MB=256
elif (( $total_mem_MB < 3900 ))
then
    echo "Configure for small instance!"
    shared_buffers_MB=512
    work_mem_MB=8
    maintenance_work_mem_MB=128
    effective_cache_size_MB=1024
fi

used_mem_global_MB=$(( $shared_buffers_MB + $maintenance_work_mem_MB ))
used_mem_connection_MB=$(( 12 + $work_mem_MB ))
max_connections=$(echo "($total_mem_MB - $used_mem_global_MB) / $used_mem_connection_MB * 0.6" | bc )
max_connections=${max_connections%.*}
effective_cache_size_MB=$( echo "$total_mem_MB * 0.4" | bc)
effective_cache_size_MB=${effective_cache_size_MB%.*}


echo "Tune postgresql.conf"
# CONNECTIONS AND AUTHENTICATION
configure_postgresql "port" "5432"
configure_postgresql "max_connections" $max_connections
configure_postgresql "superuser_reserved_connections" "5"

# RESOURCE USAGE (except WAL)
configure_postgresql "shared_buffers" "${shared_buffers_MB}MB"
configure_postgresql "work_mem" "${work_mem_MB}MB"
configure_postgresql "maintenance_work_mem" "${maintenance_work_mem_MB}MB"
configure_postgresql "shared_preload_libraries" "pg_stat_statements"

# WRITE AHEAD LOG
configure_postgresql "wal_level" "minimal"
configure_postgresql "wal_buffers" "16MB"
configure_postgresql "wal_compression" "off"
configure_postgresql "checkpoint_timeout" "5min"
configure_postgresql "max_wal_size" "4GB"
configure_postgresql "min_wal_size" "80MB"
configure_postgresql "checkpoint_completion_target" "0.7"

# AUTOVACUUM PARAMETERS
configure_postgresql "autovacuum" "on"
configure_postgresql "autovacuum_max_workers" $autovacuum_max_workers

# QUERY TUNING
configure_postgresql "random_page_cost" "4.0"
configure_postgresql "effective_cache_size" "${effective_cache_size_MB}MB"
